VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Main"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Option Explicit
'----------------------------------------------------------------------------------------------------

'----------------------------------------------------------------------------------------------------
Private Sub Worksheet_Activate()

    ActiveWindow.DisplayHeadings = False
    ActiveWindow.DisplayGridlines = False

End Sub
'----------------------------------------------------------------------------------------------------
